apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:1.6.10
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcached-service
  namespace: memcached
spec:
  ports:
  - port: 11211
    targetPort: 11211
  selector:
    app: memcached
