image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:26.1.0-dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd backend/
    - docker build -t $DOCKER_USERNAME/app_backend:v0.0.9 .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_USERNAME/app_backend:v0.0.9