apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-canary
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 5
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: x00205790/app_backend:v0.0.9
        ports:
        - containerPort: 3001
  strategy:
    canary:
      stableService: backend
      canaryService: backend-canary
      steps:
      - setWeight: 20
      - pause: {duration: 60s}
      - setWeight: 40
      - pause: {duration: 40s}
      - setWeight: 60
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 20s}

