apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-web-page
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-repo/deployments/production
    repoURL: 'git@gitlab.com:cdillon1/terraform-buildca1.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
