# ConfigMap with the HTML code for the web page
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-page
  namespace: production
data:
  index.html: |
    <html>
      <head>
        <title>Production Cluster</title>
      </head>
      <body>
        <h1>Production Cluster</h1>
      </body>
    </html>

---
# Deployment for the web server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: web-page
              mountPath: /usr/share/nginx/html
      volumes:
        - name: web-page
          configMap:
            name: web-page
            items:
              - key: index.html
                path: index.html

---
# Service for exposing the web server
apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: production
spec:
  selector:
    app: web-server
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: LoadBalancer
  loadBalancerIP: 40.127.239.44
